docker:
  registry: docker-registry.discovery.wmnet

resources:
  replicas: 1

config:
  public:
    GOMAXPROCS: "2" # Align with CPU limit to avoid throttling

app:
  version: 2026-01-07-110713-candidate-v0.10.0-dev
  limits:
    cpu: 2000m
    memory: 1Gi
  requests:
    cpu: 400m
    memory: 100Mi

external_services:
  redis-6380: [misc]

networkpolicy:
  egress:
    enabled: true
  ingress:
    enabled: true
  # selectors:
  #   service.istio.io/canonical-name: istio-ingressgateway-services
  #   istio: ingressgateway
