apiVersion: v2
description: Meta-chart for deploying Growthbook, both backend and frontend
name: growthbook
version: 0.0.24
dependencies:
  - name: growthbook-backend
    version: ">=0.0.1"
  - name: growthbook-frontend
    version: ">=0.0.1"
keywords:
  - growthbook
  - feature-flags
  - experiments
  - experiment-platform
home: https://wikitech.wikimedia.org/wiki/Test_Kitchen
sources:
  - https://github.com/growthbook/growthbook
  - https://gitlab.wikimedia.org/repos/data-engineering/growthbook/
team: https://www.mediawiki.org/wiki/Data_Platform_Engineering/Data_Platform_SRE
maintainers:
  - name: Balthazar Rouberol
    email: brouberol@wikimedia.org
  - name: Ben Tullis
    email: btullis@wikimedia.org
