apiVersion: v2
description: Helm chart for eventstreams on WMF Kubernetes infrastructure
name: eventstreams
kubeVersion: ">=1.12"
keywords:
- eventstreams
home: https://wikitech.wikimedia.org/wiki/EventStreams
sources:
- https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/services/eventstreams/+/master
maintainers:
- name: Andrew Otto
  email: otto@wikimedia.org
version: 0.4.2
