---
apiVersion: v1
appVersion: 3.7.2
description: "Container Storage Interface (CSI) driver, provisioner, snapshotter and resizer for Ceph cephfs"
name: ceph-csi-cephfs
version: 0.1.8
keywords:
  - ceph
  - cephfs
  - ceph-csi
  - operator
home: https://wikitech.wikimedia.org/wiki/Ceph
sources:
  - https://github.com/ceph/ceph-csi/tree/devel/charts/ceph-csi-cephfs
  - https://gitlab.wikimedia.org/repos/data-engineering/ceph-csi
icon: https://raw.githubusercontent.com/ceph/ceph-csi/devel/assets/ceph-logo.png
team: https://www.mediawiki.org/wiki/Data_Platform_Engineering/Data_Platform_SRE
maintainers:
  - name: Balthazar Rouberol
    email: brouberol@wikimedia.org
  - name: Ben Tullis
    email: btullis@wikimedia.org
annotations:
  # This chart is based on upstream version v3.7.2
  wmf/upstreamVersion: v3.7.2