apiVersion: v2
description: A Helm chart for Citoid on WMF Kubernetes infrastructure
kubeVersion: ">=1.8"
name: citoid
version: 0.3.0
keywords:
  - citation
  - citoid
home: https://www.mediawiki.org/wiki/Citoid
sources:
  - https://github.com/wikimedia/citoid
maintainers:
  - name: Alexandros Kosiaris
    email: akosiaris@wikimedia.org
  - name: Marielle Volz
    email: mvolz@wikimedia.org
