apiVersion: v2
name: opensearch-operator-crds
description: The OpenSearch Operator CRDs Helm chart for Kubernetes
type: application
# NOTE: version here is WMF's version of this chart.
# appVersion should be the upstream version.
# (We cannot use a '-wmf0' prerelease suffix in helm charts.
# Helm considers these 'development' versions.)
version: 0.0.2

# This is the version number of the application being deployed (the operator). This version number should be
# incremented each time you make changes to the application. The CRDs in this chart should generally be updated
# to match whatever version of the opensearch-operator is being deployed.
appVersion: 2.7.0

keywords:
  - database
  - opensearch
  - search
  - operator
  - crds
home: https://wikitech.wikimedia.org/wiki/Data_Platform/Systems/OpenSearch-on-K8s
sources:
  - https://docker-registry.wikimedia.org/repos/data-engineering/opensearch
  - https://github.com/opensearch-project/opensearch-k8s-operator/tree/main/charts/opensearch-operator
team: https://www.mediawiki.org/wiki/Data_Platform_Engineering/Data_Platform_SRE
maintainers:
  - name: Balthazar Rouberol
    email: brouberol@wikimedia.org
  - name: Brian King
    email: bking@wikimedia.org
