apiVersion: v2
description: Helm chart for the Push Notifications Service on WMF Kubernetes infrastructure
name: push-notifications
version: 0.1.9
keywords:
  - mobile
  - push
  - notifications
  - Wikimedia
home: https://www.mediawiki.org/wiki/Wikimedia_Product_Infrastructure_team/Push_Notifications_Infrastructure
sources:
  - https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/services/push-notifications/
maintainers:
  - name: Wikimedia Product Infrastructure team <https://www.mediawiki.org/wiki/Wikimedia_Product/Wikimedia_Product_Infrastructure_team>
kubeVersion: ">=1.12"
