{{- define "config.app" }}
logging:
  level: {{ .Values.app.logging.level }}

service:
  name: {{ .Values.app.service.name }}
  port: {{ .Values.app.service.port }}
  cors: {{ .Values.app.service.cors | quote }}
  max_body_size: {{ .Values.app.service.max_body_size }}
  secure_cookie: {{ .Values.app.service.secure_cookie }}
  user_agent: {{ .Values.app.service.user_agent }}

listeners:
  action_api_basepath: {{ .Values.app.listeners.action_api_basepath }}

database:
  engine: {{ .Values.app.database.engine }}
  host: {{ .Values.app.database.host }}
  database: {{ .Values.app.database.database }}
  username: {{ .Values.app.database.username }}
  port: {{ .Values.app.database.port }}

idp:
  oidc_url: {{ .Values.app.idp.oidc_url}}
  client_id: {{ .Values.app.idp.client_id }}
  redirect_uri: {{ .Values.app.idp.redirect_uri }}
  response_type: {{ .Values.app.idp.response_type }}

{{- end }}