apiVersion: v2
description: A Helm chart for a webserver for miscellaneous static sites on Kubernetes
name: miscweb
version: 0.1.0
keywords:
  - miscweb
  - miscellaneous
  - webserver
  - static
  - sites
  - html
  - apache
  - httpd
home: https://wikitech.wikimedia.org/wiki/Miscweb1002
maintainers:
  - name: Daniel Zahn
    email: dzahn@wikimedia.org
