app:
  image: repos/sre/sophroid
  version: 2026-01-29-200319
  command: [/srv/app/sophroid, --listeners=/etc/sophroid/listeners.yaml, --services=/etc/sophroid/service.yaml, --port=4252]
resources:
  replicas: 1
