apiVersion: v2
name: validating-admission-policies
description: Create Validating Admission Policies
type: application
version: 0.4.0
appVersion: "0.1.0"
# ValidatingAdmissionPolicies v1 GA since 1.30
kubeVersion: ">= 1.30"
