image: &app_image repos/data-engineering/growthbook/next
version: &app_version 2025-11-21-070713-8e67c37ca4651abfb13c1ea491ede029aa88836b@sha256:a9c28316954eb45446d761db0b803201c463eb8c7cea2d37c31e280a770813a9
app_origin: &app_origin https://growthbook-next.wikimedia.org
api_host: &api_host https://growthbook-api-next.wikimedia.org

growthbook-backend:
  app:
    image: *app_image
    version: *app_version

  config:
    public: # See https://docs.growthbook.io/self-host/env
      APP_ORIGIN: *app_origin
      API_HOST: *api_host
      EMAIL_FROM: "growthbook-next@wikimedia.org"

    oidc:
      clientId: growthbook_next
      metadata:
        authorization_endpoint: https://idp-test.wikimedia.org/oidc/oidcAuthorize
        issuer: https://idp-test.wikimedia.org/oidc
        jwks_uri: https://idp-test.wikimedia.org/oidc/jwks
        token_endpoint: https://idp-test.wikimedia.org/oidc/oidcAccessToken

  external_services:
    presto: [analytics-test]
    cas: [idp-test]

  ingress:
    gatewayHosts:
      default: "growthbook-api-next"
      extraFQDNs:
      - growthbook-api-next.wikimedia.org

growthbook-frontend:
  app:
    image: *app_image
    version:  *app_version

  config:
    public: # See https://docs.growthbook.io/self-host/env
      APP_ORIGIN: *app_origin
      API_HOST: *api_host

  ingress:
    gatewayHosts:
      default: "growthbook-next"
      extraFQDNs:
      - growthbook-next.wikimedia.org
