apiVersion: v2
description: A Helm chart for Kubernetes
name: wikifeeds
version: 0.1.3
keywords:
  - REST
  - API
  - node service
  - mobile apps
  - MediaWiki
  - Wikipedia
home: https://phabricator.wikimedia.org/tag/wikifeeds
sources:
  - https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/services/wikifeeds/
maintainers:
  - name: "Wikimedia Product Infrastructure team <https://www.mediawiki.org/wiki/Wikimedia_Product/Wikimedia_Product_Infrastructure_team>"
kubeVersion: ">=1.8"
