config:
  turnilo:
    url: https://turnilo-next.wikimedia.org
  httpd_cas_site:
    server_name: turnilo-next.wikimedia.org
    cas_login_url: https://idp-test.wikimedia.org/login
    cas_validate_url: https://idp-test.wikimedia.org/serviceValidate
    cas_root_proxied_as: https://turnilo-next.wikimedia.org

external_services:
  cas: [ idp-test ]

ingress:
  gatewayHosts:
    default: "turnilo-next"
    extraFQDNs:
    - turnilo-next.wikimedia.org