apiVersion: v2
description: A Helm chart for eventrouter (https://github.com/heptiolabs/eventrouter)
name: eventrouter
version: 0.4.2
appVersion: "0.4"
home: https://github.com/heptiolabs/eventrouter
sources:
  - https://github.com/heptiolabs/eventrouter
keywords:
  - eventrouter
maintainers:
  - name: gianrubio
    email: gianrubio@gmail.com
