app:
  version: 2026-02-16-191708-ad4447d949a8fbb2e5283bfbe02e62483922c10d@sha256:79be7ee5df18824f8c63a7f9bd8efbf00528f8aabe3431592db3af827107ea53

kerberos:
  image:
    version: 2024-08-22-120740-071bae0306d1f9ab8addd0630ca1ae6bb216a122@sha256:5a48a0fa4d9fe6ac95023b36da50a10677c8ca1857994d69e878263574702a2a

external_services:
  kerberos:
  - kdc
