
watchedNamespaces:
- postgresql-test
- cloudnative-pg-operator
- airflow-test-k8s
- airflow-wmde
- airflow-research
- airflow-search
- airflow-analytics
- airflow-analytics-test
- airflow-platform-eng
- airflow-analytics-product
- airflow-ml
