apiVersion: v2
description: A Helm chart for Test Kitchen
name: test-kitchen
version: 0.0.21
keywords:
  - experiments
  - experiment-platform
sources:
  - https://gitlab.wikimedia.org/repos/data-engineering/test-kitchen
team: https://www.mediawiki.org/wiki/Data_Platform_Engineering/Experiment_Platform
home: https://wikitech.wikimedia.org/wiki/Test_Kitchen
maintainers:
  - name: Santiago Faci
    email: sfaci@wikimedia.org
  - name: Clare Ming
    email: cming@wikimedia.org