apiVersion: v1
description: A Helm chart for Mediawiki core in a development environment
name: mediawiki-dev
version: 0.1.0
keywords:
- mediawiki
- core
home: https://www.mediawiki.org/wiki/Manual:System_administration
sources:
- https://gerrit.wikimedia.org/r/plugins/gitiles/operations/deployment-charts/+/refs/heads/master/charts/mediawiki-dev/
- https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/core/+/refs/heads/master/.pipeline/blubber.yaml
maintainers:
- name: Jeena Huneidi
  email: jhuneidi@wikimedia.org
tillerVersion: ">=2.8"
