apiVersion: v2
description: A Helm chart for the Link Recommendation Service on WMF Kubernetes.
name: linkrecommendation
version: 0.2.14
home: https://wikitech.wikimedia.org/wiki/Add_Link
sources:
  - https://gerrit.wikimedia.org/r/plugins/gitiles/research/mwaddlink/
maintainers:
  - name: Wikimedia Foundation Growth team <https://www.mediawiki.org/wiki/Growth>
kubeVersion: ">=1.12"
