apiVersion: v2
description: Resources required by the mediawiki legacy dumps jobs running in Kubernetes
name: mediawiki-dumps-legacy
version: 0.0.48
keywords:
  - mediawiki
  - dumps
  - dumpsv1
home: https://wikitech.wikimedia.org/wiki/Dumps/Airflow
team: https://www.mediawiki.org/wiki/Data_Platform_Engineering/Data_Platform_SRE
maintainers:
  - name: Balthazar Rouberol
    email: brouberol@wikimedia.org
  - name: Ben Tullis
    email: btullis@wikimedia.org