networkpolicy:
  egress:
    enabled: true
    dst_nets:
      - cidr: 123.123.123.123/24
    extraRules:
    - to:
      - podSelector:
          matchLabels:
            nicepod: 'true'
      ports:
      - protocol: TCP
        port: 1234

# The discovery stuff adds networkpolicies.
mesh:
  enabled: true
  public_port: 4004 # the port where TLS will be exposed
  tracing:
    enabled: true
    host: somewhere.else
    port: 9999
    otel_collector_namespace: alternative-otel
    otel_pod_selector:
      component: zomg
  # Enable telemetry
  telemetry:
    enabled: true
    port: 9361
discovery:
  listeners:
    - parsoid-php
    - mathoid
    - eventgate-analytics
