apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: allow-hostpath-mw-parsoid-testing
spec:
  matchConstraints:
    resourceRules:
    - apiGroups: ['']
      apiVersions: ['*']
      operations: [CREATE, UPDATE]
      resources: [pods]
  validations:
  - expression: |-
      !has(object.spec.volumes) ||
      object.spec.volumes.all(vol, has(vol.configMap) ||
      has(vol.csi) ||
      has(vol.downwardAPI) ||
      has(vol.emptyDir) ||
      has(vol.ephemeral) ||
      has(vol.persistentVolumeClaim) ||
      has(vol.projected) ||
      has(vol.secret) ||
      has(vol.hostPath))
    message: >-
      Only the following types of volumes may be used: configMap, csi, downwardAPI,
      emptyDir, ephemeral, persistentVolumeClaim, projected, secret and hostPath.
  - expression: |-
      !has(object.spec.volumes) ||
      object.spec.volumes.all(volume, (
          !has(volume.hostPath) ||
          volume.hostPath.path in ["/usr/share/GeoIP", "/usr/share/GeoIPInfo", "/srv/mediawiki", "/srv/parsoid-testing"
          ]
      ))
    message: >-
      HostPath volumes are allowed for, /usr/share/GeoIP, /usr/share/GeoIPInfo,
      /srv/mediawiki, and /srv/parsoid-testing only.
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: allow-hostpath-mw-parsoid-testing
spec:
  policyName: allow-hostpath-mw-parsoid-testing
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: pod-security.wmf.org/allow-hostpath-mw-parsoid-testing
        operator: In
        values:
        - include
  validationActions: [Deny]