apiVersion: v2
description: A Helm chart for Kubernetes
name: shellbox
version: 1.0.7
keywords:
  - shellbox
  - mediawiki
  - score
  - lilypond
home: https://www.mediawiki.org/wiki/Shellbox
sources:
  - https://gerrit.wikimedia.org/g/mediawiki/libs/Shellbox
maintainers:
  - name: Kunal Mehta
    email: legoktm@wikimedia.org
icon: https://upload.wikimedia.org/wikipedia/commons/6/6f/Shellbox_logo.png
