apiVersion: v2
name: spark-operator-crds
description: Spark Operator CRDs
type: application
# NOTE: version here is WMF's version of this chart.
# appVersion should be the upstream version.
# (We cannot use a '-wmf0' prerelease suffix in helm charts.
# Helm considers these 'development' versions.)
version: 0.0.1
appVersion: 2.2.1
icon: https://spark.apache.org/images/spark-logo.png

keywords:
  - spark
  - operator
  - crds
sources:
  - https://github.com/kubeflow/spark-operator/tree/master/charts/spark-operator-chart/crds
home: https://wikitech.wikimedia.org/wiki/Data_Platform/Systems/Spark
team: https://www.mediawiki.org/wiki/Data_Platform_Engineering/Data_Platform_SRE
maintainers:
  - name: Ben Tullis
    email: btullis@wikimedia.org
