apiVersion: v1
description: Helm chart for Chromium Render on WMF Kubernetes infrastructure
name: chromium-render
version: 0.0.2
keywords:
  - PDF
  - chromium
  - Wikimedia
home: https://www.mediawiki.org/wiki/Proton
sources:
  - https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/services/chromium-render/
maintainers:
  - name: "Wikimedia Product Infrastructure team <https://www.mediawiki.org/wiki/Wikimedia_Product/Wikimedia_Product_Infrastructure_team>"
kubeVersion: ">=1.12"
tillerVersion: ">=2.8"
