apiVersion: v2
description: A Helm chart for the Envoy-based API Gateway
name: api-gateway
version: 0.4.5
kubeVersion: ">=1.12"
keywords:
  - api-gateway
  - envoy
home: https://www.mediawiki.org/wiki/Core_Platform_Team/Initiatives/API_Gateway
maintainers:
  - name: Hugh Nowlan
    email: hnowlan@wikimedia.org
