shellbox:
  flavour: score81

service:
  deployment: production

mesh:
  enabled: true
  public_port: 4008
  tracing:
    enabled: true
    sampling: 10

resources:
  replicas: 8

config:
  public:
   FPM__log_level: debug
