apiVersion: v2
description: A Helm chart for Kubernetes
name: developer-portal
version: 0.0.7
maintainers:
  - name: Taavi Väänänen
    email: hi@taavi.wtf
  - name: Bryan Davis
    email: bd808@wikimedia.org
