kubernetesMasters:
  cidrs:
    - '10.64.16.202/32'
    - '2620:0:861:102:10:64:16:202/128'
    - '10.64.48.64/32'
    - '2620:0:861:107:10:64:48:64/128'
chartVersions:
  wmf-stable/calico: ~
  wmf-stable/calico-crds: ~
  wmf-stable/coredns: ~
  wmf-stable/cert-manager: ~