apiVersion: v2
description: A Helm chart deploying Superset
name: superset
version: 0.0.31
keywords:
  - superset
  - dataviz
  - dashboards
sources:
  - https://gitlab.wikimedia.org/repos/data-engineering/superset
team: https://www.mediawiki.org/wiki/Data_Platform_Engineering/Data_Platform_SRE
home: https://wikitech.wikimedia.org/wiki/Data_Platform/Systems/Superset/Administration
maintainers:
  - name: Ben Tullis
    email: btullis@wikimedia.org
