apiVersion: v2
description: A Helm chart for deploying Flink applications using FlinkDeployment CRD
  from flink-kubernetes-operator.
type: application
name: flink-app
version: 0.3.2
icon: https://flink.apache.org/img/logo/png/50/color_50.png
