apiVersion: v2
description: A Helm chart for deploying Flink applications using FlinkDeployment CRD from flink-kubernetes-operator.
type: application
name: flink-app
version: 0.4.33
icon: https://flink.apache.org/img/logo/png/50/color_50.png
keywords:
  - flink
home: https://wikitech.wikimedia.org/wiki/Event_Platform/Stream_Processing/Flink
sources:
  - https://gerrit.wikimedia.org/r/plugins/gitiles/operations/docker-images/production-images/+/refs/heads/master/images/flink/flink
team: https://www.mediawiki.org/wiki/Wikimedia_Search_Platform
maintainers:
  - name: Balthazar Rouberol
    email: brouberol@wikimedia.org
  - name: Ben Tullis
    email: btullis@wikimedia.org
  - name: Brian King
    email: bking@wikimedia.org
