growthbook-backend:
  config:
    public: # See https://docs.growthbook.io/self-host/env
      EMAIL_ENABLED: 'true'
      EMAIL_HOST: mx-out1001.wikimedia.org
      EMAIL_PORT: '25'

    oidc:
      # See https://docs.growthbook.io/sso
      # These values were taken from the output of `curl -s https://idp.wikimedia.org/oidc/.well-known | jq .`
      # on an idp host.
      emailDomains: [wikimedia.org]
      additionalScope: "groups"
      metadata:
        authorization_endpoint: https://idp.wikimedia.org/oidc/oidcAuthorize
        code_challenge_methods_supported: ["plain", "S256"]
        id_token_signing_alg_values_supported: [ "none", "RS256", "RS384", "RS512", "PS256", "PS384", "PS512", "ES256", "ES384", "ES512", "HS256", "HS384", "HS512" ]
        issuer: https://idp.wikimedia.org/oidc
        jwks_uri: https://idp.wikimedia.org/oidc/jwks
        token_endpoint: https://idp.wikimedia.org/oidc/oidcAccessToken

    # growthbook:  # see https://docs.growthbook.io/self-host/config
    # NOTE: Temporarily using GrowthBook UI for managing data sources

  uploads:
    volume:
      storage_class: ceph-cephfs-ssd

  external_services:
    wikimail: [mx]
    kerberos: [kdc]

  common_images:
    kerberos:
      version: 45377f59c5bdf8bae1b967c49ee29a144c5cba44-production
