apiVersion: v2
description: Helm chart for the iPoid service
name: ipoid
kubeVersion: ">=1.23"
version: 0.1.1
keywords:
  - iPoid
  - ipoid
  - IP
  - IP address
home: https://wikitech.wikimedia.org/wiki/IPoid
sources:
  - https://gitlab.wikimedia.org/repos/mediawiki/services/ipoid
maintainers:
  - name: Effie Mouzeli
    email: effie@wikimedia.org
