apiVersion: v2
description: A Helm chart for the WMF Apache Airflow instances
name: airflow
version: 0.0.163
keywords:
  - airflow
  - etl
home: https://wikitech.wikimedia.org/wiki/Data_Platform/Systems/Airflow/Kubernetes
sources:
  - https://gitlab.wikimedia.org/repos/data-engineering/airflow-dags/
team: https://www.mediawiki.org/wiki/Data_Platform_Engineering/Data_Platform_SRE
maintainers:
  - name: Balthazar Rouberol
    email: brouberol@wikimedia.org
  - name: Ben Tullis
    email: btullis@wikimedia.org
