apiVersion: v2
description: A Helm chart to deploy Turnilo behind an apache2 proxy to CAS for k8s
name: turnilo
version: 0.0.1
home: https://wikitech.wikimedia.org/wiki/Data_Platform/Systems/Turnilo
team: https://wikitech.wikimedia.org/wiki/Data_Platform_Engineering
sources:
  - https://gitlab.wikimedia.org/repos/data-engineering/turnilo/
  - https://gerrit.wikimedia.org/r/plugins/gitiles/operations/docker-images/production-images/+/refs/heads/master/images/httpd-cas/
maintainers:
  - name: Joseph Allemandou
    email: joal@wikimedia.org
  - name: Balthazar Rouberol
    email: brouberol@wikimedia.org
keywords:
  - user interface
  - analytics
  - druid
