apiVersion: v2
description: A Helm chart to deploy blunderbuss, an application ensuring the continuous deployment of required artifacts for Airflow jobs
name: blunderbuss
version: 0.0.11
keywords:
  - ci
  - artifacts
home: https://wikitech.wikimedia.org/wiki/Data_Platform/Systems/Blunderbuss
sources:
  - https://gitlab.wikimedia.org/repos/data-engineering/blunderbuss
team: https://www.mediawiki.org/wiki/Data_Platform_Engineering/Data_Engineering
maintainers:
  - name: Aleksandar Mastilovic
    email: amastilovic@wikimedia.org
