apiVersion: v1
description: Helm chart for Mathoid on WMF Kubernetes infrastructure
kubeVersion: ">=1.8"
name: mathoid
version: 0.0.13
keywords:
- math
- mathoid
home: https://www.mediawiki.org/wiki/Manual:Mathoid
sources:
- https://github.com/wikimedia/mathoid
maintainers:
- name: Alexandros Kosiaris
  email: akosiaris at wikimedia.org
tillerVersion: ">=2.8"
