apiVersion: v2
description: Helm chart for Mathoid on WMF Kubernetes infrastructure
kubeVersion: ">=1.16"
name: mathoid
version: 0.2.0
keywords:
  - math
  - mathoid
home: https://www.mediawiki.org/wiki/Manual:Mathoid
sources:
  - https://github.com/wikimedia/mathoid
maintainers:
  - name: Alexandros Kosiaris
    email: akosiaris@wikimedia.org
