replicaCount: 4

service:
  clusterIP: '10.67.64.3'

# TODO: Ideally we would spread CoreDNS pods across availability zones, but we
# will skip that step for now while on Ganeti hosts.
affinity: null
