apiVersion: v2
name: flink-kubernetes-operator-crds
description: Flink Kubernetes Operator CRDs
type: application
# NOTE: version here is WMF's version of this chart.
# appVersion should be the upstream version.
# (We cannot use a '-wmf0' prerelease suffix in helm charts.
# Helm considers these 'development' versions.)
version: 2.0.0
appVersion: 1.3.0
icon: https://flink.apache.org/img/logo/png/50/color_50.png
