prometheusScrape: false
image:
  registry: docker-registry.discovery.wmnet
  repository: kube-state-metrics
  pullPolicy: IfNotPresent
  # See T356252
  tag: 2.10.0-1-20240602

collectors:
  - cronjobs
  - daemonsets
  - deployments
  - jobs
  - leases
  - mutatingwebhookconfigurations
  - namespaces
  - nodes
  - poddisruptionbudgets
  - pods
  - replicasets
  - replicationcontrollers
  - statefulsets
  - validatingwebhookconfigurations

# Metrics to be disabled. Exact metric names and/or regex patterns.
# The allowlist and denylist are mutually exclusive.
metricDenylist:
  - kube_pod_status_qos_class
  - kube_pod_ips
  - kube_pod_tolerations

podAnnotations:
  prometheus.io/scrape: "true"

networkPolicy:
  enabled: true
  flavor: wmf

# The chart uses `namespaces` to configure namespaces to be enabled for collecting resources. We
# need to set this here to override the global variable set in admin_ng/values/<environment>. Empty
# string => all namespaces.
namespaces: ""

resources:
  limits:
   cpu: 200m
   memory: 256Mi
  requests:
   cpu: 50m
   memory: 128Mi

selfMonitor:
  enabled: true
