apiVersion: v2
description: Helm chart for Recommendation API on WMF Kubernetes infrastructure
kubeVersion: ">=1.12"
name: recommendation-api
version: 0.1.0
keywords:
- recommendation-api
sources:
- https://gerrit.wikimedia.org/g/mediawiki/services/recommendation-api
maintainers:
- name: Research Team
  email: bmansurov@wikimedia.org
