main_app:
  requests:
    cpu: 1500m
  limits:
    cpu: 2

shellbox:
  flavour: syntaxhighlight83

service:
  deployment: production

mesh:
  enabled: true
  public_port: 4014
  tracing:
    enabled: true
    sampling: 10

php:
  workers: 6

resources:
  replicas: 12
