apiVersion: v2
description: Helm chart for the maps vector tile server in WMF
name: tegola-vector-tiles
version: 0.1.5
kubeVersion: '>=1.16'
keywords:
  - maps
  - vector-tiles
  - vector-server
  - tegola
home: https://wikitech.wikimedia.org/wiki/Maps
maintainers:
  - name: 'Wikimedia Product Infrastructure team <https://www.mediawiki.org/wiki/Wikimedia_Product/Wikimedia_Product_Infrastructure_team>'
