apiVersion: v2
name: cloudnative-pg-crds
description: Cloudnative PG Operator CRDs
type: application
# NOTE: version here is WMF's version of this chart.
# appVersion should be the upstream version.
# (We cannot use a '-wmf0' prerelease suffix in helm charts.
# Helm considers these 'development' versions.)
version: 0.1.2
appVersion: "0.21.5"
keywords:
  - cloudnative-pg
  - operator
  - crds
icon: https://raw.githubusercontent.com/cloudnative-pg/artwork/main/cloudnativepg-logo.svg
team: https://www.mediawiki.org/wiki/Data_Platform_Engineering/Data_Platform_SRE
sources:
  - https://github.com/cloudnative-pg/charts/tree/main/charts/cloudnative-pg/templates/crds
home: https://wikitech.wikimedia.org/wiki/Data_Platform/Systems/CloudnativePG
maintainers:
  - name: Balthazar Rouberol
    email: brouberol@wikimedia.org
  - name: Ben Tullis
    email: btullis@wikimedia.org
