apiVersion: v2
description: Helm chart for datasets-config on dse-k8s infrastructure
name: datasets-config
kubeVersion: ">=1.12"
keywords:
  - config
home: https://gitlab.wikimedia.org/repos/data-engineering/dataset-config-store-service
sources:
  - https://gitlab.wikimedia.org/repos/data-engineering/dataset-config-store-service
maintainers:
  - name: Thomas Chin
    email: tchin@wikimedia.org
  - name: Gabriele Modena
    email: gmodena@wikimedia.org
version: 0.0.9
