apiVersion: v2
description: A Helm chart for CXServer on WMF Kubernetes infrastructure
name: cxserver
kubeVersion: ">=1.8"
version: 0.1.9
keywords:
- cxserver
- language
- translation
home: https://www.mediawiki.org/wiki/Content_translation/cxserver
sources:
- https://github.com/wikimedia/mediawiki-services-cxserver
maintainers:
- name: Alexandros Kosiaris
  email: akosiaris@wikimedia.org
- name: Kartik Mistry
  email: kmistry@wikimedia.org
