apiVersion: v2
description: A Helm chart for CXServer on WMF Kubernetes infrastructure
name: cxserver
kubeVersion: ">=1.8"
version: 0.3.12
keywords:
  - cxserver
  - language
  - translation
home: https://wikitech.wikimedia.org/wiki/Cxserver
sources:
  - https://github.com/wikimedia/mediawiki-services-cxserver
team: https://wikitech.wikimedia.org/wiki/Language_and_Product_Localization
maintainers:
  - name: Alexandros Kosiaris
    email: akosiaris@wikimedia.org
  - name: Kartik Mistry
    email: kmistry@wikimedia.org
