apiVersion: v2
description: An auxiliary service for generating histograms from Redis databases.
name: redioscope
version: 0.2.1
keywords:
  - api-gateway
  - redis
home: https://gitlab.wikimedia.org/repos/mediawiki/services/redioscope
maintainers:
  - name: Daniel Kinzler
    email: dkinzler@wikimedia.org
