{{/*
  Permit port 9300 (cluster state) information between clusters, the operator, istio etc.
*/}}
---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  {{- include "base.meta.metadata" (dict "Root" .) | indent 2 }}
spec:
  selector: 'has(opster.io/opensearch-cluster)'
  ingress:
    - action: Allow
      protocol: TCP
      source:
        namespaceSelector: 'kubernetes.io/metadata.name in {"{{ $.Release.Namespace }}", "istio-system", "opensearch-operator"}'
      destination:
        ports:
          # transport (cluster state)
          - 9300

{{/*
  Permit port 9200 without restrictions.
*/}}
---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Namespace }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  selector: 'has(opster.io/opensearch-cluster)'
  types:
    - Ingress
  ingress:
    - action: Allow
      protocol: TCP
      destination:
      # OpenSearch REST API
        ports:
          - 9200

{{- if .Values.networkpolicy.egress.enabled }}
{{/* NetworkPolicy for ingress/egress traffic managed via our internal templates */}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  {{- include "base.meta.metadata" (dict "Root" .) | indent 2 }}
spec:
  podSelector:
    matchExpressions:
    - key: opster.io/opensearch-cluster
      operator: Exists
  policyTypes:
    - Egress
  egress:
    {{- include "base.networkpolicy.egress-basic" .Values }}
{{- end }}
