apiVersion: v2
description: Run kafka mirrormaker v1 in Kubernetes
name: kafka-mirrormaker
version: 0.0.3
keywords:
  - kafka
  - mirroring
  - mirrormaker
home: https://wikitech.wikimedia.org/wiki/Kafka
sources:
  - https://gitlab.wikimedia.org/repos/data-engineering/kafka/
team: https://www.mediawiki.org/wiki/Data_Platform_Engineering/Data_Platform_SRE
maintainers:
  - name: Balthazar Rouberol
    email: brouberol@wikimedia.org