apiVersion: v2
description: A Helm chart for FerretDB, a mongodb-compatible database using PostgreSQL as a backend
name: ferretdb
version: 0.0.1
keywords:
  - database
  - mongodb
  - postgresql
home: https://wikitech.wikimedia.org/wiki/Data_Platform/Systems/FerretDB
sources:
  - https://github.com/FerretDB/FerretDB
  - https://gitlab.wikimedia.org/repos/data-engineering/ferretdb
team: https://www.mediawiki.org/wiki/Data_Platform_Engineering/Data_Platform_SRE
maintainers:
  - name: Balthazar Rouberol
    email: brouberol@wikimedia.org
  - name: Ben Tullis
    email: btullis@wikimedia.org
