apiVersion: v1
description: Helm chart for the Page Content Service (mobileapps) on WMF Kubernetes
  infrastructure
name: mobileapps
version: 0.0.10
keywords:
- mobile
- page content
- Wikimedia
home: https://www.mediawiki.org/wiki/Wikimedia_Apps/Team/RESTBase_services_for_apps
sources:
- https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/services/mobileapps/
maintainers:
- name: "Wikimedia Product Infrastructure team <https://www.mediawiki.org/wiki/Wikimedia_Product/Wikimedia_Product_Infrastructure_team>"
kubeVersion: ">=1.12"
tillerVersion: ">=2.8"
