{{/*
  In order to allow Airflow to create pods in a spark-enabled namespace, we need to do the following:

* Define a Role granting suitable permissions in the release namespace
* Create a RoleBinding object that is bound to the airflow ServiceAccount in each of the permitted namespaces

*/}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  {{- include "base.meta.labels" . | indent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-job-orchestration
  namespace: {{ $.Release.Namespace }}
  {{- include "base.meta.labels" . | indent 2 }}
rules:
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-job-orchestration
  namespace: {{ $.Release.Namespace }}
  {{- include "base.meta.labels" . | indent 2 }}
roleRef:
  kind: Role
  name: spark-job-orchestration
  apiGroup: rbac.authorization.k8s.io
subjects:
{{ range $namespace, $service_accounts := $.Values.orchestrator.service_accounts }}
{{ range $service_account := $service_accounts }}
- kind: ServiceAccount
  name: {{ $service_account }}
  namespace: {{ $namespace }}
{{- end }}
{{- end }}
{{/*
  Spark driver pods are required to have additional permissions within a namespace.
  See: https://spark.apache.org/docs/3.5.7/running-on-kubernetes.html#rbac for more details

* We create a ServiceAccount named spark.
* We create a Role defining the required and any optional permissions that we wish to use.
* We create a RoleBinding that binds this role to the spark ServiceAccount in the namespace.

  This ServiceAccount will be configured for use automatically by the spark-defaults.conf configmap.
*/}}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-driver-role
  namespace: {{ $.Release.Namespace }}
  {{- include "base.meta.labels" . | indent 2 }}
rules:
# The spark driver is required to create and manage executor pods.
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/status"]
  verbs: ["*"]
# The spark driver will create a headless service for the driver, when run in client mode.
- apiGroups: [""]
  resources: ["services"]
  verbs: ["*"]
# The spark driver can manage persistent volume claims.
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["*"]
# The spark driver can manage configmaps for dependencies.
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["*"]
# The spark driver can manage secrets to include kerberos delegation tokens.
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
# The spark driver can check the limits of the namespace.
- apiGroups: [""]
  resources: ["resourcequotas", "limitranges"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-driver-rolebinding
  namespace: {{ $.Release.Namespace }}
  {{- include "base.meta.labels" . | indent 2 }}
roleRef:
  kind: Role
  name: spark-driver-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: spark
  namespace: {{ $.Release.Namespace }}
