{{/*
  In order to allow Airflow to create pods in a spark-enabled namespace, we need to do the following:

* Define a Role granting suitable permissions in the release namespace
* Create a RoleBinding object that is bound to the airflow ServiceAccount in each of the permitted namespaces

*/}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-job-orchestration
  namespace: {{ $.Release.Namespace }}
  {{- include "base.meta.labels" . | indent 2 }}
rules:
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-job-orchestration
  namespace: {{ $.Release.Namespace }}
  {{- include "base.meta.labels" . | indent 2 }}
roleRef:
  kind: Role
  name: spark-job-orchestration
  apiGroup: rbac.authorization.k8s.io
subjects:
{{ range $namespace, $service_accounts := $.Values.orchestrator.service_accounts }}
{{ range $service_account := $service_accounts }}
- kind: ServiceAccount
  name: {{ $service_account }}
  namespace: {{ $namespace }}
{{- end }}
{{- end }}
