apiVersion: v2
name: opensearch-cluster
description: A Helm chart for OpenSearch Cluster
type: application

## The opensearch-cluster Helm Chart version
version: 0.0.17

## The operator version
appVersion: 2.7.0

keywords:
  - database
  - opensearch
  - search
home: https://wikitech.wikimedia.org/wiki/Data_Platform/Systems/OpenSearch-on-K8s
sources:
  - https://docker-registry.wikimedia.org/repos/data-engineering/opensearch
  - https://github.com/opensearch-project/opensearch-k8s-operator/tree/main/charts/opensearch-cluster
team: https://www.mediawiki.org/wiki/Data_Platform_Engineering/Data_Platform_SRE
maintainers:
  - name: Balthazar Rouberol
    email: brouberol@wikimedia.org
  - name: Brian King
    email: bking@wikimedia.org
