apiVersion: v2
description: Support resources intended to be deployed in a namespace hosting Spark jobs
name: spark-support
version: 0.0.34
keywords:
  - spark
  - sparkapplication
team: https://www.mediawiki.org/wiki/Data_Platform_Engineering/Data_Platform_SRE
home: https://wikitech.wikimedia.org/wiki/Data_Platform/Systems/Spark
maintainers:
  - name: Ben Tullis
    email: btullis@wikimedia.org
