apiVersion: v2
description: A chart to deploy the growthbook backend
name: growthbook-backend
version: 0.0.23
keywords:
  - growthbook
  - feature-flags
  - experiments
  - experiment-platform
home: https://wikitech.wikimedia.org/wiki/Test_Kitchen
sources:
  - https://github.com/growthbook/growthbook
  - https://gitlab.wikimedia.org/repos/data-engineering/growthbook/
team: https://www.mediawiki.org/wiki/Data_Platform_Engineering/Data_Platform_SRE
maintainers:
  - name: Balthazar Rouberol
    email: brouberol@wikimedia.org
  - name: Ben Tullis
    email: btullis@wikimedia.org
