apiVersion: v1
description: Helm chart for Wikibase Termbox SSR on WMF Kubernetes infrastructure
name: termbox
version: 0.0.16
kubeVersion: ">=1.8"
keywords:
- wikidata
- ssr
- termbox
home: https://wikitech.wikimedia.org/wiki/WMDE/Wikidata/SSR_Service
sources:
- https://gerrit.wikimedia.org/g/wikibase/termbox/
maintainers:
- name: Alexandros Kosiaris
  email: akosiaris@wikimedia.org
- name: Thomas Arrow
  email: thomas.arrow_ext@wikimedia.de
- name: Leszek Manicki
  email: leszek.manicki@wikimedia.de
tillerVersion: ">=2.8"
