apiVersion: v2
description: A Helm chart to deploy the Spark history server on Kubernetes
name: spark-history
version: 0.0.19
keywords:
  - spark
  - yarn
  - spark-history
  - hdfs
home: https://wikitech.wikimedia.org/wiki/Analytics/Systems/Cluster/Spark_History
sources:
  - https://gerrit.wikimedia.org/r/plugins/gitiles/operations/docker-images/production-images/+/refs/heads/master/images/spark/3.4/
team: https://www.mediawiki.org/wiki/Data_Platform_Engineering/Data_Platform_SRE
maintainers:
  - name: Balthazar Rouberol
    email: brouberol@wikimedia.org
  - name: Ben Tullis
    email: btullis@wikimedia.org
